import { E2EPage, E2ETestCaseRow, E2ECaseItem, TestFramework, E2EGenContext } from '../models/E2EDto';
import { librariesNs, classesNs, testsNs } from './generatedNamespaces';
import { mapCaptureType } from './e2eCaseLogic';
import { chooseSendMethod, chooseExtractMethod } from './e2eMethodSelection';

/**
 * E2E test generation — turns an explicit, user-authored chain (E2ECaseItem[]) into a
 * framework-correct, compilable C# test file. Send methods pair with the Class row directly below
 * them (the class supplies URL + body / {placeholder} values). Shared across editions.
 */

interface GenState { lastResponse: string | null; tipShown: boolean; varTypes?: Map<string, string> }

/** PascalCase, identifier-safe test method name from a free-text case name. */
export function methodName(name: string): string {
  const cleaned = (name || 'TestCase').replace(/[^a-zA-Z0-9]+/g, ' ').trim()
    .split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  return /^[a-zA-Z]/.test(cleaned) ? cleaned : `Test${cleaned}`;
}

const attrFor = (f: TestFramework) => (f === 'NUnit' ? '[Test]' : f === 'xUnit' ? '[Fact]' : '[TestMethod]');
const assertTrue = (f: TestFramework, expr: string) => (f === 'xUnit' ? `Assert.True(${expr});` : `Assert.IsTrue(${expr});`);
const isAsync = (returnType: string) => /^task\b|^task</i.test((returnType || '').trim());
const returnsResponse = (returnType: string) => /httpresponsemessage/i.test(returnType || '');
const returnsBool = (returnType: string) => /\bbool\b/i.test(returnType || '');
const cleanEndpoint = (e: string) => (e || '').replace(/\s*\([A-Za-z]+\)\s*$/, '').trim();

const producedVar = (item: E2ECaseItem, n: number) =>
  item.assignTo?.trim() || (item.type === 'Class' ? `response${n}` : `result${n}`);

function urlExpr(endpoint: string, n: number, bindVar?: string): string {
  if (bindVar && /\{[^}]+\}/.test(endpoint)) {
    const [before, after = ''] = endpoint.split(/\{[^}]+\}/);
    let expr = `baseUrl + "${before}" + ${bindVar}`;
    if (after) expr += ` + "${after}"`;
    return expr;
  }
  return `baseUrl + "${endpoint}"`;
}

/** Find a property's declared C# type in the generated class code (defaults to string). */
function csTypeOf(classCode: string, prop: string): string {
  const m = (classCode || '').match(new RegExp(`public\\s+([A-Za-z0-9_<>\\?\\[\\]]+)\\s+${prop}\\b`));
  return m ? m[1] : 'string';
}

/** Emit a single override value: a variable reference as-is, else a type-aware literal. */
function overrideValue(v: { value: string; isVariable?: boolean }, type: string): string {
  if (v.isVariable) return v.value;
  const t = (type || '').toLowerCase();
  if (/\bbool\b/.test(t)) return /^true$/i.test(v.value.trim()) ? 'true' : 'false';
  if (/(int|long|short|byte|decimal|double|float)/.test(t)) return v.value.trim();
  return JSON.stringify(v.value);
}

/**
 * Build an object-initializer (` { Prop = value, ... }`) from a Class step's per-test overrides,
 * so a test can pin specific fields while the class keeps generating the rest. Empty when none.
 */
function classInitializer(item: E2ECaseItem | undefined, ctx: E2EGenContext): string {
  const ov = item?.overrides;
  if (!ov) return '';
  const code = (ctx.classes.find((c: any) => c.className === item!.ref)?.classCode) || '';
  const parts = Object.entries(ov)
    .filter(([, v]) => v && v.value !== '' && v.value != null)
    .map(([prop, v]) => `${prop} = ${overrideValue(v as { value: string; isVariable?: boolean }, csTypeOf(code, prop))}`);
  return parts.length ? ` { ${parts.join(', ')} }` : '';
}

/**
 * Comment lines placed above a request class: a one-time tip explaining how to pin field values
 * per-test (with a concrete example from the class), plus a note of any fields pinned in this test.
 */
function overrideComment(classItem: E2ECaseItem | undefined, ctx: E2EGenContext, state: GenState): string[] {
  if (!classItem) return [];
  const cls = ctx.classes.find((c: any) => c.className === classItem.ref);
  if (!cls) return [];
  const out: string[] = [];
  if (!state.tipShown) {
    const firstProp = (cls.classCode || '').match(/public\s+[A-Za-z0-9_<>?[\]]+\s+([A-Za-z0-9_]+)\s*\{\s*get;\s*set;/)?.[1] || 'Field';
    out.push(`        // Tip: pin field values for just this test with an object initializer —`);
    out.push(`        //   e.g. new ${classItem.ref} { ${firstProp} = "value" }. Unset fields are auto-generated by the Data Library.`);
    state.tipShown = true;
  }
  const pinned = classItem.overrides
    ? Object.keys(classItem.overrides).filter(k => (classItem.overrides as any)[k]?.value !== '' && (classItem.overrides as any)[k]?.value != null)
    : [];
  if (pinned.length) out.push(`        // Fields pinned for this test: ${pinned.join(', ')}.`);
  return out;
}

function classStep(item: E2ECaseItem, n: number, f: TestFramework, ctx: E2EGenContext, state: GenState, lines: string[]): void {
  const cls = ctx.classes.find((c: any) => c.className === item.ref);
  const endpoint = cleanEndpoint(cls?.endpoint || '/');
  const httpMethod = (cls?.method || 'POST').toUpperCase();
  const respVar = producedVar(item, n);
  // Core owns the verb+content-type → send-method mapping (E2E-SEL-1). Deriving it here keeps GET/DELETE/
  // POST/PUT/PATCH × json/form all correct from one source, instead of an inline block that had drifted
  // (PATCH fell through to POST; a form-encoded PUT sent JSON).
  const sendMethod = chooseSendMethod(httpMethod, cls?.contentType);

  // URL: bind every {placeholder} from the class's own `args` (In params), so a class-first row supports
  // multi-placeholder paths (e.g. /store/{storeId}/order/{orderId}). Fall back to the single legacy
  // `pathBindVariable`, then to the bare endpoint.
  const hasPlaceholders = /\{[^}]+\}/.test(endpoint);
  const url = hasPlaceholders && placeholdersIn(endpoint).some(name => item.args?.[name]?.value)
    ? buildUrlWithPathArgs(endpoint, item)
    : urlExpr(endpoint, n, item.pathBindVariable);

  lines.push(`        // Step ${n}: ${item.ref} (${httpMethod} ${endpoint})`);
  lines.push(`        var url${n} = ${url};`);

  if (httpMethod === 'GET') {
    lines.push(`        var ${respVar} = await ${sendMethod}<object>(token, url${n});`);
    state.lastResponse = respVar; // a GET response is capturable too (E2E-CAP-GET)
  } else if (httpMethod === 'DELETE') {
    lines.push(`        var ${respVar} = await ${sendMethod}(token, url${n});`);
    state.lastResponse = respVar;
  } else {
    overrideComment(item, ctx, state).forEach(c => lines.push(c));
    lines.push(`        var request${n} = new ${item.ref}()${classInitializer(item, ctx)};`);
    // `…FormAsync` serialises the request as a form body, everything else as JSON.
    const body = /FormAsync$/.test(sendMethod) ? `request${n}.ToFormBody()` : `request${n}.ToJson()`;
    lines.push(`        var ${respVar} = await ${sendMethod}(token, url${n}, ${body});`);
    state.lastResponse = respVar;
  }

  const capturedCount = emitCaptures(item, respVar, lines);
  // Defaulted response method (E2E-SEL-1): the user's rule — "the response method is defaulted". If the step
  // captured a field it has already extracted it; otherwise assert the call succeeded (DELETE → the 200/204
  // validator, every other verb → the 200/201 validator). Core owns which validator, so all editions agree.
  if (capturedCount === 0) {
    const validate = chooseExtractMethod('', httpMethod); // no field → a Validate*ResponseAsync
    lines.push(`        ${assertTrue(f, `await ${validate}(${respVar})`)}`);
  }
}

/**
 * OUT captures (E2E-CAP-1): the user's typed rows on a Class step, each capturing a response field into a
 * variable converted to the user-chosen store-as `type`. Core owns this — the client only supplies the rows.
 * One typed `ExtractFields<T>` line per row, reading THIS step's response (so later steps can use the value).
 * The type is what the user selects (e.g. an id stored as `long`, a status as `string`); it is not inferred.
 */
function emitCaptures(item: E2ECaseItem, respVar: string, lines: string[]): number {
  let emitted = 0;
  for (const c of item.captures || []) {
    const variable = c?.variable?.trim();
    if (!variable) continue;
    const type = mapCaptureType(c.type, 'csharp');
    lines.push(`        var ${variable} = await ExtractFields<${type}>(${respVar}, "${(c.fieldPath || '').trim()}");`);
    emitted += 1;
  }
  return emitted;
}

function argExpr(a?: { value: string; isVariable?: boolean }): string | null {
  if (!a || !a.value) return null;
  return a.isVariable ? a.value : JSON.stringify(a.value);
}

function placeholdersIn(endpoint: string): string[] {
  return [...endpoint.matchAll(/\{([^}]+)\}/g)].map(m => m[1]);
}

function buildUrlWithPathArgs(endpoint: string, classItem?: E2ECaseItem): string {
  const parts = endpoint.split(/(\{[^}]+\})/).filter(p => p.length > 0);
  let expr = 'baseUrl';
  for (const part of parts) {
    const m = part.match(/^\{([^}]+)\}$/);
    expr += m ? ` + ${argExpr(classItem?.args?.[m[1]]) || `/* ${m[1]} */`}` : ` + "${part}"`;
  }
  return expr;
}

function classPlaceholderExpr(classItem: E2ECaseItem | undefined, ctx: E2EGenContext): string | null {
  if (!classItem) return null;
  const ep = cleanEndpoint(ctx.classes.find((x: any) => x.className === classItem.ref)?.endpoint || '');
  const names = placeholdersIn(ep);
  if (!names.length) return null;
  return argExpr(classItem.args?.[names[0]]) || `/* ${names[0]} */`;
}

function methodTakesUrl(ref: string, ctx: E2EGenContext): boolean {
  const m = ctx.methods.find((x: any) => x.methodName === ref);
  return (m?.parameters || '').toLowerCase().includes('url');
}

function resolveArg(param: string, item: E2ECaseItem, state: GenState, ctx: E2EGenContext, pairedClass?: E2ECaseItem): string {
  const lp = param.toLowerCase();
  if (lp.includes('token')) return 'token';
  if (lp === 'response') return item.responseVar || state.lastResponse || `/* ${param} */`;
  if (lp.includes('url')) {
    const cn = pairedClass?.ref || item.classRef;
    const ep = cn
      ? cleanEndpoint(ctx.classes.find((x: any) => x.className === cn)?.endpoint || '')
      : (item.endpoint || '');
    if (!lp.includes('template') && /\{[^}]+\}/.test(ep)) return buildUrlWithPathArgs(ep, pairedClass);
    return `baseUrl + "${ep}"`;
  }
  if (lp.includes('body')) {
    const cn = pairedClass?.ref || item.classRef || item.bodyClass;
    if (!cn) return `/* ${param} */`;
    const c = ctx.classes.find((x: any) => x.className === cn);
    const isForm = lp.includes('formbody') || /x-www-form-urlencoded/i.test(c?.contentType || '');
    return `new ${cn}()${classInitializer(pairedClass, ctx)}.${isForm ? 'ToFormBody' : 'ToJson'}()`;
  }
  const a = item.args?.[param];
  if (a && a.value) return a.isVariable ? a.value : JSON.stringify(a.value);
  return `/* ${param} */`;
}

function methodStep(item: E2ECaseItem, n: number, f: TestFramework, ctx: E2EGenContext, state: GenState, lines: string[], pairedClass?: E2ECaseItem): void {
  const m = ctx.methods.find((x: any) => x.methodName === item.ref);
  const params: string[] = (m?.parameters || '')
    .split(',').map((p: string) => p.trim()).filter(Boolean).map((p: string) => p.split(':')[0].trim());
  const hasUrlTemplate = params.some((p: string) => { const lp = p.toLowerCase(); return lp.includes('url') && lp.includes('template'); });
  const phExpr = classPlaceholderExpr(pairedClass, ctx);
  const args = params.map((p: string) =>
    (p.toLowerCase() === 'value' && hasUrlTemplate && phExpr) ? phExpr : resolveArg(p, item, state, ctx, pairedClass));
  const awaited = isAsync(m?.returnType) ? 'await ' : '';
  const resultVar = producedVar(item, n);
  // Option 1: a field-extracting method whose captured variable feeds a TYPED (non-string) request field is
  // emitted as the generic `ExtractField<T>` so the value is captured in its native type (e.g. a decimal id),
  // dropping into that field with no conversion. Everything else keeps the plain string extractor.
  const extractsField = params.some((p: string) => { const lp = p.toLowerCase(); return lp.includes('field') || lp.includes('path'); });
  const wantType = extractsField ? state.varTypes?.get(resultVar) : undefined;
  const emitRef = wantType ? `ExtractFields<${wantType}>` : item.ref;
  const call = `${emitRef}(${args.join(', ')})`;

  lines.push(`        // Step ${n}: ${item.ref}`);
  if (pairedClass) overrideComment(pairedClass, ctx, state).forEach(c => lines.push(c));
  if (/^validate/i.test(item.ref) && returnsBool(m?.returnType)) {
    lines.push(`        ${assertTrue(f, `${awaited}${call}`)}`);
  } else {
    lines.push(`        var ${resultVar} = ${awaited}${call};`);
    if (returnsResponse(m?.returnType)) state.lastResponse = resultVar;
  }
}

/** Generate a framework-correct, compilable C# test file from one ordered E2E chain. */
export function generateTestForRow(row: E2ETestCaseRow, page: E2EPage, ctx: E2EGenContext): string {
  const f = page.framework;
  const tokenObj = ctx.methods.find((m: any) => m.methodName === page.token);
  const tokenLine = isAsync(tokenObj?.returnType)
    ? `        var token = await ${page.token}();`
    : `        var token = ${page.token}();`;

  const state: GenState = { lastResponse: null, tipShown: false };

  // Look-ahead (Option 1): map each captured variable to the type of the body field it later feeds, so the
  // extract can capture it in that native type. Only body-field overrides matter — a URL {placeholder} bound
  // to a variable only ever goes into string concatenation, so it stays a string.
  const varTypes = new Map<string, string>();
  for (const it of (row.items || [])) {
    if (it.type !== 'Class' || !it.overrides) continue;
    const code = ctx.classes.find((c: any) => c.className === it.ref)?.classCode || '';
    for (const [prop, v] of Object.entries(it.overrides)) {
      const ov = v as { value: string; isVariable?: boolean };
      if (!ov?.isVariable || !ov.value) continue;
      const t = csTypeOf(code, prop);
      if (t && t.toLowerCase() !== 'string') varTypes.set(ov.value, t);
    }
  }
  state.varTypes = varTypes;

  const steps: string[] = [];
  const items = row.items || [];

  const consumed = new Set<number>();
  items.forEach((item, i) => {
    if (item.type === 'Method' && methodTakesUrl(item.ref, ctx) && items[i + 1]?.type === 'Class') {
      consumed.add(i + 1);
    }
  });

  let n = 0;
  items.forEach((item, i) => {
    if (item.type === 'Class') {
      if (consumed.has(i)) return;
      n += 1;
      classStep(item, n, f, ctx, state, steps);
    } else {
      n += 1;
      const next = items[i + 1];
      const pairedClass = methodTakesUrl(item.ref, ctx) && next?.type === 'Class' ? next : undefined;
      methodStep(item, n, f, ctx, state, steps, pairedClass);
    }
    steps.push('');
  });

  while (steps.length && steps[steps.length - 1] === '') steps.pop();

  const fwUsing = f === 'NUnit' ? 'using NUnit.Framework;'
    : f === 'xUnit' ? 'using Xunit;'
    : 'using Microsoft.VisualStudio.TestTools.UnitTesting;';
  const classAttr = f === 'NUnit' ? '[TestFixture]' : f === 'xUnit' ? '' : '[TestClass]';

  const methodBlock = [
    `    ${attrFor(f)}`,
    `    public async Task ${methodName(row.name)}()`,
    `    {`,
    `        var baseUrl = ${page.basePath}();`,
    tokenLine,
    ``,
    ...steps,
    `    }`,
  ];
  const nested = methodBlock.map(l => (l ? '    ' + l : l));

  return [
    'using System;',
    'using System.Net.Http;',
    'using System.Threading.Tasks;',
    fwUsing,
    `using static ${librariesNs()}.ApiMethods;`, // helper methods are called by bare name
    `using ${classesNs(page.application)};`,      // request classes (e.g. new StripePostCustomers())
    '',
    `namespace ${testsNs(page.application)}`,
    '{',
    ...(classAttr ? [`    ${classAttr}`] : []),
    `    public class ${methodName(row.name)}Tests`,
    '    {',
    ...nested,
    '    }',
    '}',
  ].join('\n');
}
