/**
 * TS-C5 — TypeScript counterpart to {@link generateDataLibraryCode}. Emits `dataGenerator.ts`: a single
 * `DataGenerator` class the request classes call as `new DataGenerator().method()` (TS-C4), backed by
 * the `@faker-js/faker` singleton instead of Bogus.
 *
 * Like the C# version, each method's `code` is a COMPLETE TS instance method, pasted verbatim (not
 * re-wrapped) — the bodies come from the TS seed library (TS-C8) or the user's own methods and reference
 * the imported `faker`. faker is a dependency of the generated PROJECT (declared in its package.json),
 * not of api2test-core — core only emits the `import`.
 */
import { DataMethodCode } from './generateDataLibrary';

export function generateDataLibraryTypeScript(methods: DataMethodCode[], _root?: string): string {
  const indent = (text: string) => text.split('\n').map((l) => (l.length ? '  ' + l : l)).join('\n');

  const body = (methods || []).map((m) => {
    const code = (m.code || `${m.methodName}(): unknown { throw new Error('Not implemented: ${m.methodName}'); }`).trim();
    const doc = m.description ? `  /** ${m.description.replace(/\n/g, ' ')} */\n` : '';
    return doc + indent(code);
  }).join('\n\n');

  return `// Auto-generated by API2Test. Do not edit by hand.
import { faker } from '@faker-js/faker';

/**
 * Generates field values for test data (the Data Library). Request classes call it as
 * \`new DataGenerator().method()\`.
 */
export class DataGenerator {
${body}
}
`;
}
