/**
 * TypeScript counterpart to {@link generateApiMethodsCSharp} — renders the API Method Library as a
 * single `apiMethods.ts`: a `ApiMethods` class of static fetch wrappers, plus a `Reporter` that prints
 * the same `##A2T_CALL##` markers the runner ({@link parseApiCalls}) extracts. Keeping the class name +
 * static-method shape identical to the C# output means the test/E2E emitters resolve
 * `wrapperClass.wrapperMethod` the same way in both languages.
 */
import { ApiMethodForGeneration, CSharpGenerationOptions } from './generateApiMethodsCSharp';

/**
 * Generate the complete `apiMethods.ts` source. `options.className` names the class (default
 * `ApiMethods`); `options.namespace` is ignored (TS uses module exports, not namespaces).
 */
export function generateApiMethodsTypeScript(
  methods: ApiMethodForGeneration[],
  options: CSharpGenerationOptions = {},
): string {
  const { className = 'ApiMethods', includeApiClient = true } = options;

  const tokenMethods = methods.filter((m) => m.methodName.toLowerCase().includes('token'));
  const otherMethods = methods.filter((m) => !m.methodName.toLowerCase().includes('token'));

  let ts = `// Auto-generated by API2Test. Do not edit by hand.\n\n`;
  ts += `export class ${className} {\n`;

  if (includeApiClient) {
    ts += `  // Base HTTP client methods (fetch-based). Each reports its call via the Reporter.
  static async postWithToken(url: string, authToken: string, jsonBody: unknown): Promise<Response> {
    const jsonContent = JSON.stringify(jsonBody);
    const headers: Record<string, string> = { Accept: 'application/json', 'Content-Type': 'application/json' };
    if (authToken) { headers.Authorization = \`Bearer \${authToken}\`; }
    const response = await fetch(url, { method: 'POST', headers, body: jsonContent });
    return Reporter.record('POST', url, jsonContent, response);
  }

  static async getWithToken(url: string, authToken: string): Promise<Response> {
    const headers: Record<string, string> = { Accept: 'application/json' };
    if (authToken) { headers.Authorization = \`Bearer \${authToken}\`; }
    const response = await fetch(url, { method: 'GET', headers });
    return Reporter.record('GET', url, null, response);
  }

  static async putWithToken(url: string, authToken: string, jsonBody: unknown): Promise<Response> {
    const jsonContent = JSON.stringify(jsonBody);
    const headers: Record<string, string> = { Accept: 'application/json', 'Content-Type': 'application/json' };
    if (authToken) { headers.Authorization = \`Bearer \${authToken}\`; }
    const response = await fetch(url, { method: 'PUT', headers, body: jsonContent });
    return Reporter.record('PUT', url, jsonContent, response);
  }

  static async deleteWithToken(url: string, authToken: string): Promise<Response> {
    const headers: Record<string, string> = { Accept: 'application/json' };
    if (authToken) { headers.Authorization = \`Bearer \${authToken}\`; }
    const response = await fetch(url, { method: 'DELETE', headers });
    return Reporter.record('DELETE', url, null, response);
  }

  /** Parse a successful JSON response body as T; throws on a non-2xx status. */
  static async getResponseContent<T>(response: Response): Promise<T> {
    if (!response.ok) { throw new Error(\`Request failed with status: \${response.status}\`); }
    return (await response.json()) as T;
  }

`;
  }

  if (tokenMethods.length > 0) {
    ts += `  // Authentication and Token Methods\n`;
    ts += tokenMethods.map((m) => methodFromCode(m)).join('\n');
    ts += '\n';
  }

  if (otherMethods.length > 0) {
    ts += `  // Additional API Methods\n`;
    ts += otherMethods.map((m) => methodFromCode(m)).join('\n');
  }

  // Typed field extraction (E2E-CAP-1) used to be appended here as a second `extractFields` on top of the
  // library's `extractFieldFromResponse` — one operation under two names. The curated `ExtractFieldAsync`
  // now takes the store-as type itself, so it is emitted from the library like every other method.
  ts += `}

/**
 * Captures each API call (request + response) so the local/CI runner can extract it from the test's
 * console output. \`record\` reads the response body off a clone, so the caller's own \`response.json()\`
 * still works. Never throws — reporting must not fail a test.
 */
export class Reporter {
  private static readonly maxBody = 16384;

  static async record(method: string, url: string, requestBody: string | null, response: Response): Promise<Response> {
    try {
      let responseBody: string | null = null;
      try { responseBody = await response.clone().text(); } catch { responseBody = null; }
      const call = {
        method,
        url,
        requestBody: Reporter.cap(requestBody),
        status: response ? response.status : 0,
        responseBody: Reporter.cap(responseBody),
      };
      console.log('##A2T_CALL## ' + JSON.stringify(call));
    } catch { /* reporting must never fail a test */ }
    return response;
  }

  private static cap(s: string | null): string | null {
    return s != null && s.length > Reporter.maxBody ? s.substring(0, Reporter.maxBody) + '\\u2026(truncated)' : s;
  }
}
`;

  return ts;
}

/** Render one custom library method inside the class body — pastes its TS `code`, re-indented. */
function methodFromCode(method: ApiMethodForGeneration): string {
  const indent = '  ';
  let out = '';
  if (method.description) {
    out += `${indent}/** ${method.description.replace(/\n/g, ' ')} */\n`;
  }
  if (method.code && method.code.trim()) {
    const body = method.code
      .split('\n')
      .map((line) => (line.trim() ? `${indent}${line}` : line))
      .join('\n');
    out += `${body}\n\n`;
  } else {
    const returnType = method.returnType || 'void';
    const parameters = method.parameters || '';
    out += `${indent}static ${method.methodName}(${parameters}): ${returnType} {\n`;
    out += `${indent}  // TODO: Implement ${method.methodName}\n`;
    out += `${indent}  throw new Error('Not implemented: ${method.methodName}');\n`;
    out += `${indent}}\n\n`;
  }
  return out;
}
