/**
 * PY-GEN-1 — Python counterpart to {@link generateDataLibraryTypeScript}. Emits `data_generator.py`:
 * a single `DataGenerator` class the request classes call as `DataGenerator().method()`, backed by
 * Faker + a random.Random instance instead of Bogus/@faker-js.
 *
 * Each method's `code` is a COMPLETE Python instance method (`def first_name(self) -> str:`), pasted
 * indented into the class body — the bodies come from the Python seed library or the user's own
 * methods and reference `self._fake` (Faker) and `self._rng` (random.Random). faker is a dependency
 * of the generated PROJECT (declared in its requirements), not of api2test-core.
 */
import { DataMethodCode } from './generateDataLibrary';
import { pySymbol } from './pyNaming';

export function generateDataLibraryPython(methods: DataMethodCode[], _root?: string): string {
  const indent = (text: string) => text.split('\n').map((l) => (l.length ? '    ' + l : l)).join('\n');

  const body = (methods || []).map((m) => {
    const code = (m.code || `def ${pySymbol(m.methodName)}(self):\n    raise NotImplementedError("${m.methodName}")`).trim();
    const doc = m.description ? `    # ${m.description.replace(/\n/g, ' ')}\n` : '';
    return doc + indent(code);
  }).join('\n\n');

  return `# Auto-generated by API2Test. Do not edit by hand.
import json
import random
import string
import uuid
from datetime import date, datetime, timedelta

from faker import Faker


class DataGenerator:
    """Generates field values for test data (the Data Library). Request classes call it as
    DataGenerator().method()."""

    def __init__(self):
        self._fake = Faker()
        self._rng = random.Random()

${body}
`;
}
