/**
 * PY-GEN-1 — Python counterpart to {@link generateRequestClassTypeScript}. Renders a request-body
 * class from an API Class Library entry.
 *
 * Python specifics:
 *  - the attribute name IS the JSON key (`self.firstName = ...` keeps the API's casing — correctness
 *    over PEP8 style); a key that is not a valid identifier is set via `setattr(self, "pet-id", ...)`;
 *  - an optional, unassigned field is simply NOT assigned, so `vars(self)` (the JSON source) omits it;
 *  - `to_json()` serialises `vars(self)` — instance attributes only, methods are never included.
 *
 * The class is deployed to `Classes/<App>/`; it imports its siblings from `Libraries/` as packages
 * (the generated test bootstraps sys.path to the deploy root, and Python 3.3+ namespace packages need
 * no __init__.py).
 */
import { FieldConfiguration, ClassGenerationRequest } from '../models/ClassGenerationDto';
import { NOT_ASSIGNED, PARAMETER } from './DataDictionaryService';
import { pySymbol, isPyIdentifier } from './pyNaming';

const isFormEncoded = (ct?: string) => (ct || '').toLowerCase().includes('x-www-form-urlencoded');

export function generateRequestClassPython(request: ClassGenerationRequest): string | null {
  const className = resolveClassName(request);
  const bodyFields = request.fieldConfigurations.filter((f) => (f.location || 'body') === 'body');

  if (bodyFields.length === 0) {
    const urlParams = request.fieldConfigurations.filter((f) => ['path', 'query', 'header'].includes(f.location || ''));
    if (urlParams.length === 0) { return null; }
    return generateUrlParamClass(className, request, urlParams);
  }

  return generateBodyClass(className, bodyFields, request);
}

function generateBodyClass(className: string, fields: FieldConfiguration[], request: ClassGenerationRequest): string {
  const usesData = fields.some(hasAssignedMethod);
  const isForm = isFormEncoded(request.contentType);
  const imports = [
    'import json',
    '',
    usesData ? 'from Libraries.data_generator import DataGenerator' : null,
    isForm ? 'from Libraries.api_methods import form_url_encode' : null,
  ].filter((l) => l !== null);
  while (imports[imports.length - 1] === '') { imports.pop(); }

  const assignments = fields.map((f) => generateAssignment(f)).filter((l) => l !== null) as string[];
  const initBody = assignments.length ? assignments : ['        pass'];

  const toFormBody = isForm
    ? `

    def to_form_body(self):
        """Serialises this instance to an application/x-www-form-urlencoded body (used by form APIs like Stripe)."""
        return form_url_encode(vars(self))`
    : '';

  return `# Auto-generated by API2Test. Do not edit by hand.
${imports.join('\n')}


class ${className}:
    """Request body class for the API endpoint.
    Attributes initialised with DataGenerator calls produce realistic test data automatically.
    Optional attributes (no data method assigned) are not set and are omitted from the JSON body."""

    def __init__(self):
${initBody.join('\n')}

    def to_json(self):
        """Serialises this instance to a JSON string for use as a request body."""
        return json.dumps(vars(self))${toFormBody}
`;
}

/**
 * BODY-LESS endpoint → one attribute per URL/header parameter, set by the generated test. Plain
 * attributes defaulting to None, no to_json() (URL params are never a JSON body).
 */
function generateUrlParamClass(className: string, request: ClassGenerationRequest, params: FieldConfiguration[]): string {
  const lines = params.map((p) => `        ${assignFor(p.name, 'None')}  # supplied by the generated test`);
  return `# Auto-generated by API2Test. Do not edit by hand.


class ${className}:
    """URL/header parameters for ${(request.method || '').toUpperCase()} ${request.endpoint}.
    The generated test supplies these values and interpolates them into the request URL."""

    def __init__(self):
${lines.join('\n')}
`;
}

/** One __init__ assignment (or null for an optional, unassigned field — omitted from the body). */
function generateAssignment(field: FieldConfiguration): string | null {
  if (hasAssignedMethod(field)) {
    return `        ${assignFor(field.name, dataCall(field))}`;
  }

  if (field.dataMethod === PARAMETER) {
    // Value supplied at runtime (e.g. another API's output) — settable attribute with a safe default.
    return `        ${assignFor(field.name, emptyDefault(field.type))}  # parameter — value supplied at runtime`;
  }

  if (field.required) {
    return `        ${assignFor(field.name, emptyDefault(field.type))}  # TODO: assign a data method in the Data Dictionary`;
  }

  // Optional, unassigned — not set, so vars(self) omits it (the API uses its own default).
  return null;
}

/** OVR-CASE (Py half): the raw JSON key stays the attribute name; setattr when it is not an identifier. */
function assignFor(name: string, expr: string): string {
  return isPyIdentifier(name) ? `self.${name} = ${expr}` : `setattr(self, ${JSON.stringify(name)}, ${expr})`;
}

function dataCall(field: FieldConfiguration): string {
  const args = (field.dataMethodArgs || '').trim();
  return `DataGenerator().${pySymbol(field.dataMethod!)}(${args})`;
}

function hasAssignedMethod(field: FieldConfiguration): boolean {
  return !!(field.dataMethod
    && field.dataMethod.trim() !== ''
    && field.dataMethod !== NOT_ASSIGNED
    && field.dataMethod !== PARAMETER);
}

function emptyDefault(type: string): string {
  switch ((type || '').toLowerCase()) {
    case 'int': case 'integer': case 'decimal': case 'number': case 'double': return '0';
    case 'bool': case 'boolean': return 'False';
    case 'array': case 'object': return 'None';
    default: return '""';
  }
}

function resolveClassName(request: ClassGenerationRequest): string {
  const raw = request.className || deriveClassName(request.application, request.endpoint);
  return sanitizeClassName(raw);
}

function deriveClassName(application: string, endpoint: string): string {
  const appPart = application.replace(/\s+/g, '');
  const endpointPart = endpoint
    .replace(/^\//, '')
    .split('/')
    .filter((p) => p && !p.startsWith('{') && !p.startsWith(':'))
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).replace(/[-_]/g, ''))
    .join('') || 'Resource';
  return `${appPart}${endpointPart}`;
}

function sanitizeClassName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]/g, '');
  if (!cleaned) { return 'GeneratedClass'; }
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}
