/**
 * TS-C4 — TypeScript counterpart to {@link ClassGenerationService.renderClassCode} (the emitter path).
 * Renders a request-body class from an API Class Library entry.
 *
 * TS lets us drop two C# devices:
 *  - no `[JsonPropertyName]` — the property name *is* the JSON key (quoted when it isn't a valid identifier);
 *  - no `[JsonIgnore(WhenWritingNull)]` — `JSON.stringify` omits `undefined` properties automatically,
 *    so an optional, unassigned field is just `name?: T` (left undefined).
 *
 * Mirrors the flat body-class and URL-param-class branches of the C# emitter. Form-encoded `toFormBody()`
 * is NOT emitted yet (needs a TS `FormUrlEncode` helper) — see TASKS.md TS-C4 follow-up.
 */
import { FieldConfiguration, ClassGenerationRequest } from '../models/ClassGenerationDto';
import { NOT_ASSIGNED, PARAMETER } from './DataDictionaryService';
import { tsSymbol } from './tsNaming';

export function generateRequestClassTypeScript(request: ClassGenerationRequest): string | null {
  const className = resolveClassName(request);
  const bodyFields = request.fieldConfigurations.filter((f) => (f.location || 'body') === 'body');

  if (bodyFields.length === 0) {
    const urlParams = request.fieldConfigurations.filter((f) => ['path', 'query', 'header'].includes(f.location || ''));
    if (urlParams.length === 0) { return null; }
    return generateUrlParamClass(className, request, urlParams);
  }

  return generateBodyClass(className, bodyFields);
}

function generateBodyClass(className: string, fields: FieldConfiguration[]): string {
  const usesData = fields.some(hasAssignedMethod);
  const importLine = usesData ? `import { DataGenerator } from './dataGenerator';\n\n` : '';
  const properties = fields.map((f) => '  ' + generateProperty(f)).join('\n');

  return `// Auto-generated by API2Test. Do not edit by hand.
${importLine}/**
 * Request body class for the API endpoint.
 * Properties initialised with DataGenerator calls produce realistic test data automatically.
 * Optional properties (no data method assigned) are left undefined and omitted from the JSON body.
 */
export class ${className} {
${properties}

  /** Serialises this instance to a JSON string for use as a request body. */
  toJson(): string { return JSON.stringify(this); }
}
`;
}

/**
 * BODY-LESS endpoint → one property per URL/header parameter, set by the generated test. Plain
 * properties, no `toJson()` (URL params are never a JSON body). Definite-assignment `!` satisfies
 * strict `strictPropertyInitialization` — the test supplies every value before use.
 */
function generateUrlParamClass(className: string, request: ClassGenerationRequest, params: FieldConfiguration[]): string {
  const lines = params.map((p) => `  ${propKey(p.name)}!: ${tsType(p.type)};`);
  return `// Auto-generated by API2Test. Do not edit by hand.

/**
 * URL/header parameters for ${(request.method || '').toUpperCase()} ${request.endpoint}.
 * The generated test supplies these values and interpolates them into the request URL.
 */
export class ${className} {
${lines.join('\n')}
}
`;
}

/** One class property. Property name is the JSON key (quoted when not a valid identifier). */
function generateProperty(field: FieldConfiguration): string {
  const key = propKey(field.name);
  const type = tsType(field.type);

  if (hasAssignedMethod(field)) {
    return `${key}: ${type} = ${dataCall(field)};`;
  }

  if (field.dataMethod === PARAMETER) {
    // Value supplied at runtime (e.g. another API's output) — settable property with a safe default.
    return `${key}: ${type} = ${emptyDefault(field.type)}; // parameter — value supplied at runtime`;
  }

  if (field.required) {
    return `${key}: ${type} = ${emptyDefault(field.type)}; // TODO: assign a data method in the Data Dictionary`;
  }

  // Optional, unassigned — left undefined, so JSON.stringify omits it (API uses its own default).
  return `${key}?: ${type};`;
}

function dataCall(field: FieldConfiguration): string {
  const args = (field.dataMethodArgs || '').trim();
  return `new DataGenerator().${tsSymbol(field.dataMethod!)}(${args})`;
}

function hasAssignedMethod(field: FieldConfiguration): boolean {
  return !!(field.dataMethod
    && field.dataMethod.trim() !== ''
    && field.dataMethod !== NOT_ASSIGNED
    && field.dataMethod !== PARAMETER);
}

/** A field name usable as-is, or quoted when it isn't a valid JS identifier (keeps the exact JSON key). */
function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : `'${name.replace(/'/g, "\\'")}'`;
}

function tsType(type: string): string {
  switch ((type || '').toLowerCase()) {
    case 'string': return 'string';
    case 'int': case 'integer': case 'decimal': case 'number': case 'double': return 'number';
    case 'bool': case 'boolean': return 'boolean';
    case 'datetime': case 'date': return 'string';
    // object/array hold whatever the assigned data method returns — `unknown` accepts any value and,
    // as a declared type, still serialises correctly.
    case 'array': case 'object': return 'unknown';
    default: return 'string';
  }
}

function emptyDefault(type: string): string {
  switch ((type || '').toLowerCase()) {
    case 'int': case 'integer': case 'decimal': case 'number': case 'double': return '0';
    case 'bool': case 'boolean': return 'false';
    case 'array': case 'object': return 'null as unknown';
    default: return "''";
  }
}

function resolveClassName(request: ClassGenerationRequest): string {
  const raw = request.className || deriveClassName(request.application, request.endpoint);
  return sanitizeClassName(raw);
}

function deriveClassName(application: string, endpoint: string): string {
  const appPart = application.replace(/\s+/g, '');
  const endpointPart = endpoint
    .replace(/^\//, '')
    .split('/')
    .filter((p) => p && !p.startsWith('{') && !p.startsWith(':'))
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).replace(/[-_]/g, ''))
    .join('') || 'Resource';
  return `${appPart}${endpointPart}`;
}

function sanitizeClassName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9]/g, '');
  if (!cleaned) { return 'GeneratedClass'; }
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}
