/**
 * PY-GEN-1 — Python counterpart to {@link generateApiMethodsTypeScript}. Renders the API Method
 * Library as a single `api_methods.py`.
 *
 * Shape differs from C#/TS deliberately: the curated Python seed writes MODULE-LEVEL functions
 * (`def post_json_async(token, url, json_body):`), not class statics — so the module IS the library
 * and callers write `api_methods.post_json_async(...)`. The seed bodies call `requests` directly and
 * report through the module-level `reporter` instance, whose `record(response)` derives method/url/
 * request body from `response.request` (requests keeps the prepared request on the response) and
 * prints the same `##A2T_CALL##` marker the runner ({@link parseApiCalls}) extracts.
 */
import { ApiMethodForGeneration, CSharpGenerationOptions } from './generateApiMethodsCSharp';
import { pySymbol } from './pyNaming';

/**
 * Generate the complete `api_methods.py` source. `options.className`/`namespace`/`includeApiClient`
 * are accepted for signature parity with the C#/TS generators but unused — Python has no wrapper
 * class and the seed carries its own send helpers.
 */
export function generateApiMethodsPython(
  methods: ApiMethodForGeneration[],
  _options: CSharpGenerationOptions = {},
): string {
  const tokenMethods = methods.filter((m) => m.methodName.toLowerCase().includes('token'));
  const otherMethods = methods.filter((m) => !m.methodName.toLowerCase().includes('token'));

  let py = `# Auto-generated by API2Test. Do not edit by hand.
import json
import os
import re
import urllib.parse

import requests


class _Reporter:
    """Captures each API call (request + response) so the local/CI runner can extract it from the
    test's stdout. Derives the request details from response.request (requests keeps the prepared
    request on every response). Never raises - reporting must not fail a test."""

    MAX_BODY = 16384

    def record(self, response):
        try:
            request = getattr(response, "request", None)
            body = getattr(request, "body", None)
            if isinstance(body, bytes):
                body = body.decode("utf-8", errors="replace")
            call = {
                "method": getattr(request, "method", None),
                "url": getattr(request, "url", None),
                "requestBody": self._cap(body),
                "status": getattr(response, "status_code", 0),
                "responseBody": self._cap(getattr(response, "text", None)),
            }
            print("##A2T_CALL## " + json.dumps(call))
        except Exception:
            pass  # reporting must never fail a test
        return response


    def _cap(self, s):
        if s is not None and len(s) > self.MAX_BODY:
            return s[: self.MAX_BODY] + "\\u2026(truncated)"
        return s


reporter = _Reporter()


`;

  if (tokenMethods.length > 0) {
    py += `# Authentication and Token Methods\n`;
    py += tokenMethods.map((m) => methodFromCode(m)).join('\n');
  }

  if (otherMethods.length > 0) {
    py += `# Additional API Methods\n`;
    py += otherMethods.map((m) => methodFromCode(m)).join('\n');
  }

  return py;
}

/** Render one library method at module level — pastes its Python `code` verbatim, else a stub. */
function methodFromCode(method: ApiMethodForGeneration): string {
  let out = '';
  if (method.description) {
    out += `# ${method.description.replace(/\n/g, ' ')}\n`;
  }
  if (method.code && method.code.trim()) {
    out += `${method.code.replace(/\s+$/, '')}\n\n`;
  } else {
    const params = (method.parameters || '')
      .split(',').map((p) => p.trim()).filter(Boolean)
      .map((p) => pySymbol(p.split(':')[0].trim()))
      .join(', ');
    out += `def ${pySymbol(method.methodName)}(${params}):\n`;
    out += `    # TODO: Implement ${method.methodName}\n`;
    out += `    raise NotImplementedError("${method.methodName}")\n\n`;
  }
  return out;
}
